# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Martin McDougall
title: Senior IT Security Manager
email: martin@mcdougall.dk
website: profile.mcdougall.dk

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: wetn0odle
github_username:  lykkeleif
#instagram_username: ---
linkedin_username: martinmcdougall
#youtube_username: ---

additional_links:

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Martin!
  Throughout my life, I've been working in retail. I was absolutely enchanted by the feeling of community and solidarity, so I ended up starting my career here.
  
  Deep down, I've always been a nerd, so after working my way up through the retail business, I ended up in a headquarter function as a consultant before (finally!) transitioning into IT.
  
  When I managed to land a job in security, I knew I had struck gold. The everchanging threat landscape; the balancing of cost vs. benefit; the complex problems that needed to be communicated in a way so the audience understood... I was enthrawled.
  
  So here I am. Enjoying every day doing what I am deeply passionated about. 

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Wrote and implemented ISO27002 policy
        quote: >
          Building the foundation for a modern security programme
        description: | # this will include new lines to allow paragraphs
          Buying security gadgets and software is not what makes you secure. 
          Combining the different aspects of information security into a streamlined, standardized policy paved the road to
          further improve our security posture. 

          By taking a top-down approach, we methodically went through all the domains and ensured that we had a written 
          policy on each area, and at the same time that they were complementing each other and not contradicting each other.

          Although writing a policy can be tricky, the real battle is the implementation in the business. A written policy provides
          nothing if the organization does not live by it.
          In all honesty, you're never done implementing a policy. It's an continuous process to ensure compliance in both existing
          as well as new processes, products and employees.
      
      - layout: top-middle
        title: Implementation of Microsoft E5 EMS Suite
        #link: ---
        # link_text: Project Website
        additional_links:
          - title:  Microsoft EMS E5
            #icon: fab fa-github
            url: https://www.microsoft.com/en-us/security/business/enterprise-mobility-security
        quote: >
          Ambitious move to raise the security level across multiple domains 
        description: | # this will include new lines to allow paragraphs
          Raising security in a cost-focused enterprise can be tricky. Without any larger incidents, the benefits of further investments into 
          security product are hard to leverage.

          By building threat scenarios based on real-life scenarios happening within the previous year, we were able to build a common
          understanding of the risks of doing nothing. After that we could move on to discuss the alternatives.
          Selecting the right product was essential, and by ensuring compatability with both inhouse skillsets, daily operations,
          as well as the ambitions and requirements from our security policies & strategy, we went with the Microsoft E5 EMS solution.


  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Salling Group
        link: sallinggroup.com
        # link_text: 
        sub_title: Senior Manager, Group IT Security
        caption: December 2018 - Present
        quote: >
          Managing security and compliance in a multinational retail group.
        description: | 
          Together with my team of incredibly talented specialists, we're working on keeping a high level of security in a fast-paced company in a constantly changing industry.
          
          When working in a very cost-focused environment, I quickly learnt to balance cost vs. benefit. One of my first actions when starting in the position was to go through every process and every delivery in the team to ensure that only the ones adding value remained. 
          
          This ensured maximum output and a highly motivated team, since they felt their work made a change!

          My areas of responsibility include:
           - IT Auditing
           - Security compliance (PCI DSS, EU GDPR, ISO27000)
           - Security incident response

      - layout: left
        title: Salling Group
        link: sallinggroup.com
        # link_text: 
        sub_title: Business Relations Manager, eCommerce & Digital Development
        caption: May 2016 - November 2018
        quote: >
          Coordination development pipeline and priorities for eCommerce and digital products, as well as internal customer managment.
        description: | 
          As business relations manager for the eCommerce and digital development, I was the liaison between the IT department and
          the digital development department. 

          Managing and coordinating the efforts between a large (at the time) predominantly waterfall-oriented organization, and an
          extremely agile smaller department was no easy task in itself, but when ends met, we were able to deliver awesome solutions
          together!

      - layout: left
        title: føtex, a part of Salling Group
        link: foetex.dk
        # link_text: 
        sub_title: Management Consultant
        caption: July 2012 - April 2016
        quote: >
          Creating business insights through numbers crunching, reporting and business process optimization.
        description: | 
          Originally starting out as a junior consultant, I was primarilly tasked with converting large amounts of data into consumable
          reports for audiences across the organization; from the CEO to the department managers out in the individual stores.

          The reporting branched out into the creation of internal tools to ease the daily work of our stores by minimizing the amount
          of time they needed to spend in front of a screen instead of servicing our customers.

          By the end of my time as a management consultant i føtex, I had created a centralized controlling setup which serviced all stores
          every week with key insights into their performance (operational, sales, waste, etc.).

      - layout: left
        title: føtex and Bilka, a part of Salling Group
        link: bilka.dk
        # link_text: 
        sub_title: Various positions in sales, operations and management
        caption: July 2006 - June 2012
        quote: >
          Building the foundation of who I am today
        description: | 
          Working in the stores largely made me who I am today. It taught me about the versatility of people, and gave me a 
          healthy amount of respect for my fellow colleagues and customers. 

          Although I do not miss working in a store today, I would have never done without it - and if I were to be given the
          possibility to rewind time, I would do it all again! 

#  - title: Education # Title for the section
#    layout: list # Type of content section (list/text)
#    content:
#      - layout: left
#        title: Harvard University
#        caption: 2010 - 2013
#        sub_title: BSc Computer Science
#        quote: >
#          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
#        description: | # this will include new lines to allow paragraphs
#          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.
#
#          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Even though I'm deeply passioned about my profession, there's more to life than work.
      My family is without a doubt the most important element in my life - I'm definitely a family-man.
      Privately I live together with my girlfriend and our little dog in our new house.


      That being said, I'm also a nerd in my free time. I enjoy a good game, both board and video.
      
      Other than that I enjoy learning new stuff and a good challenge is always welcome. 

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
